language: go

sudo: required
dist: trusty

go:
  - "1.7"

install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh
  - glide install

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)